import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Jaro, JetBrains_Mono } from 'next/font/google'
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

// Configuration Jaro
const jaro = Jaro({
  subsets: ['latin'],
  variable: '--font-jaro',
  weight: ['400'],
  display: 'swap',
})

// Configuration JetBrains Mono
const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains',
  weight: ['300', '400', '600', '800'],
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Emma Vaysse - Développeuse Web",
    description: "Découvrez mes projets et compétences en développement web",
    url: "https://emmavaysse.fr",
    siteName: "Emma Vaysse Portfolio",
    images: [
      {
        url: "./assets/projects-img/portfolio.png",
        width: 1200,
        height: 630,
        alt: "Emma Vaysse Portfolio",
      },
    ],
    locale: "fr_FR",
    type: "website",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${geistSans.variable} ${geistMono.variable} ${jaro.variable} ${jetbrainsMono.variable}`}>
      <body
        className={`${jetbrainsMono.className} antialiased min-h-screen flex flex-col bg-primary`}
      >
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}