import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Jaro, JetBrains_Mono } from 'next/font/google'
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

// Configuration Jaro
const jaro = Jaro({
  subsets: ['latin'],
  variable: '--font-jaro',
  weight: ['400'], // Jaro n'a qu'un seul poids disponible
  display: 'swap',
})

// Configuration JetBrains Mono
const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains',
  weight: ['300', '400', '600', '800'], // Tous les poids que vous utilisez
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jaro.variable} ${jetbrainsMono.variable} antialiased flex flex-col m-0 bg-primary`}
      >
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
